[package]
name = "lwk_bindings"
version = "0.3.0"
edition = "2021"
description = "Liquid Wallet Kit - Bindings for other languages"
license = "MIT OR BSD-2-Clause"
documentation = "https://docs.rs/lwk_bindings"

[dependencies]
elements = "0.24.0"
thiserror = "1.0.50"
uniffi = { version = "0.26.1", features = ["bindgen-tests"] }
lwk_wollet = { version = "0.4.0" }
lwk_common = { version = "0.4.0" }
lwk_signer = { version = "0.4.0" }
serde_json = "1"
lwk_test_util = { version = "0.3.0" }

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[lib]
crate-type = ["cdylib", "rlib"]
name = "lwk"

[features]
foreign_bindings = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
